# Generated by Django 5.0 on 2024-01-04 04:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('team_one', models.CharField(max_length=100)),
                ('team_two', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_type', models.CharField(choices=[('AAU', 'AAU'), ('HS', 'High School')], max_length=5)),
                ('season_start_date', models.DateField(blank=True, null=True)),
                ('season_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField(verbose_name=[django.core.validators.MinValueValidator(48), django.core.validators.MaxValueValidator(96)])),
                ('weight', models.PositiveIntegerField(verbose_name=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(450)])),
                ('aau_team_name', models.CharField(max_length=100, null=True)),
                ('high_school_team_name', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('high_school_graduation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameHighlightVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='player_game_highlights/')),
                ('video_name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('rebounds', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('turnovers', models.PositiveIntegerField(default=0)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('steals', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('total_rebounds', models.PositiveIntegerField(default=0)),
                ('total_assists', models.PositiveIntegerField(default=0)),
                ('total_turnovers', models.PositiveIntegerField(default=0)),
                ('total_blocks', models.PositiveIntegerField(default=0)),
                ('total_steals', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.season')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.season'),
        ),
    ]
