# Generated by Django 5.0 on 2024-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_video_upload', '0002_remove_coach_user_remove_player_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamehighlightvideo',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playergamestatistic',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playergamestatistic',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerseasonstatistic',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerseasonstatistic',
            name='season',
        ),
        migrations.AddField(
            model_name='playergamehighlightvideo',
            name='game_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='playergamehighlightvideo',
            name='team_playing_against',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playergamehighlightvideo',
            name='team_playing_for',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='PlayerGameStatistic',
        ),
        migrations.DeleteModel(
            name='PlayerSeasonStatistic',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
