# Generated by Django 5.0 on 2024-01-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_video_upload', '0003_remove_playergamehighlightvideo_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamehighlightvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='playergamehighlightvideo',
            name='s3_object_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
