# Generated by Django 5.0 on 2024-01-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_video_upload', '0004_remove_playergamehighlightvideo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_coaching',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
