# Generated by Django 5.0 on 2024-01-08 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_video_upload', '0006_game_playergamehighlightvideo_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamehighlightvideo',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playergamestatistic',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.profile'),
        ),
        migrations.AlterField(
            model_name='playergamestatistic',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.game'),
        ),
    ]
