# Generated by Django 5.0 on 2024-01-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_video_upload', '0007_remove_playergamehighlightvideo_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamehighlightvideo',
            name='game_date',
        ),
    ]
