# Generated by Django 5.0 on 2024-01-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_video_upload', '0008_remove_playergamehighlightvideo_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamehighlightvideo',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.profile'),
        ),
        migrations.AddField(
            model_name='playergamestatistic',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketball_video_upload.profile'),
        ),
    ]
